spring.application.name=ProjectManagementSystem
#接続用URL
spring.datasource.url=jdbc:mariadb://localhost/project_management
#MariaDBのドライバ設定
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#ユーザ名
spring.datasource.username=root
#パスワード
spring.datasource.password=


spring.security.user.name=admin
spring.security.user.password=pass123
spring.security.user.roles=ADMIN

#スプリングセキュリティーの有効を切り替え（dev: 無効、　prod：有効）
#spring.profiles.active=dev
 spring.profiles.active=prod

#JPA設定
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true